version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: ni
    ports:
      - 8080:8080
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: no
    ports:
      - 1025:1025   # SMTP server
      - 8025:8025   # Web interface